### ISSUE TITLE
Cura 5.0 App Crash when trying to edit materials

### ISSUE THREAD

**Issue by marin2020** [tdwiser/ffc3pro_cura#1]
Crashing the app when trying to edit materials:
![image](https://user-images.githubusercontent.com/43380506/179250248-15025111-3004-4d6c-a39a-de2b2c96353f.png)

App version:
![image](https://user-images.githubusercontent.com/43380506/179249552-50fbf2f2-631c-48b5-88b6-44d7bdb092d6.png)

Error traceback:
Traceback (most recent call last):
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 84, in setKey
    self._update()
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 148, in _update
    new_properties[property_name] = self._getPropertyValue(property_name)
  File "UM\Settings\Models\ContainerPropertyProvider.py", line 167, in _getPropertyValue
    property_value = SettingDefinition.settingValueToString(setting_type, property_value)
  File "UM\Settings\SettingDefinition.py", line 619, in settingValueToString
    return convert_function(value)
  File "UM\Settings\SettingDefinition.py", line 757, in <lambda>
    "float": {"from": lambda v: str(round(float(v), 4)) if v is not None else "", "to": toFloatConversion, "validator": Validator},
TypeError: float() argument must be a string or a real number, not 'SettingFunction'

Logs:
Thread 0x000058dc (most recent call first):
  File "C:\Program Files\Ultimaker Cura 5.0.0\share\cura\plugins\USBPrinting\USBPrinterOutputDeviceManager.py", line 88 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005804 (most recent call first):
  File "threading.py", line 324 in wait
  File "zeroconf\__init__.py", line 2534 in wait
  File "zeroconf\__init__.py", line 1715 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00002e48 (most recent call first):
  File "threading.py", line 324 in wait
  File "threading.py", line 600 in wait
  File "C:\Program Files\Ultimaker Cura 5.0.0\share\cura\plugins\UM3NetworkPrinting\src\Network\ZeroConfClient.py", line 81 in _handleOnServiceChangedRequests
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000598c (most recent call first):
  File "zeroconf\__init__.py", line 1369 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000058f8 (most recent call first):
  File "C:\Program Files\Ultimaker Cura 5.0.0\share\cura\plugins\RemovableDriveOutputDevice\RemovableDrivePlugin.py", line 61 in _updateThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00000700 (most recent call first):
  File "UM\Backend\Backend.py", line 165 in _storeStderrToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000001a4 (most recent call first):
  File "UM\Backend\Backend.py", line 153 in _storeOutputToLogThread
  File "threading.py", line 946 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001470 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000553c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00001770 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000059ec (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003b10 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000043e0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005b00 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004118 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x0000059c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000049dc (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005490 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00005990 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00003e54 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000054b0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x00004d7c (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Thread 0x000044a0 (most recent call first):
  File "threading.py", line 320 in wait
  File "threading.py", line 460 in acquire
  File "UM\JobQueue.py", line 98 in _nextJob
  File "UM\JobQueue.py", line 124 in run
  File "threading.py", line 1009 in _bootstrap_inner
  File "threading.py", line 966 in _bootstrap

Current thread 0x00004f58 (most recent call first):
  File "cura\CrashHandler.py", line 396 in _logInfoWidget
  File "cura\CrashHandler.py", line 182 in _createDialog
  File "cura\CrashHandler.py", line 86 in __init__
  File "cura_app.py", line 164 in exceptHook
  File "UM\Qt\QtApplication.py", line 403 in exec
  File "cura\CuraApplication.py", line 879 in run
  File "cura_app.py", line 238 in <module>

**Comment by tdwiser** [comment]
@marin2020 as far as I can tell this issue is with @Ultimaker/Cura, not this printer profile. However I had a similar crash/hang at some point and it was due to a cheap USB webcam being plugged in. Unplugging the webcam resolving the issue. Hope that helps.

**Comment by marin2020** [comment]
> it was due to a cheap USB webcam being plugged in. 

I don't get the relation between the two things. Looking at the error it looks like the expected type is not the same. Without this plugin, Cura works just fine. I don't see your point. You are probably not familiar with software development. I hoped you can "trace" the issue and fix it. Sorry to bother you!

**Comment by tdwiser** [comment]
Apologies, I read the error log and traceback as well as your steps to reproduce and did not see any references to this profile or its plugin script, so I misunderstood. I am reopening the issue. Can you please specify which material property you are editing when the crash happens so I can investigate?

**Comment by marin2020** [comment]
It crashes right away. Steps to reproduce:
Choose FlashForge Creator 3 Pro, then choose  Extruder 1, then the "Material" Dropdown which has PLA selected, and once the drop-down is opened, choose "Manage Materials". The "Preferences" Dialog opens with "Materials" selected and "Generic PLA" selected. A second later the Crash dialog appears and once closed the whole Cura App closes.
BTW: I've just found there is Cura version 5.1.0. Same problem there.
I also tried it on two different computers. -> same.

**Comment by tdwiser** [comment]
Thank you for the details, I was able to reproduce this on my local machine (macOS/Cura 4.13) as well. Somehow I didn't encounter this in my prior use of the profile as I never visited that particular settings page. I've pushed a patch that will hopefully fix the crash; please try out 1bb2e74 and let me know if it resolves this issue.

**Comment by marin2020** [comment]
The change solved the issue. Thanks a lot!
I wish I can contribute as well, but I am so new in 3D printing (in fact I am afraid of breaking my Creator 3 Pro with some bad G-Code. Once I did smash the nozzle into the plate on one Creality CR10-V3)
And also I don't know how the different Python components work. Maybe one day...
Thanks again. I'll give it a try.
